name: Publish

on:
  workflow_call:
    inputs:
      environment:
        description: 'Hosting environment'
        required: true
        type: string

jobs:
  publish:
    uses: mink-psi/private-test/.github/workflows/publish.yml@main
