name: Publish

on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.PROJECT_REPO_SECRET }}"
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      environment: production
